image: python:3.6

stages:
  - test

test_cli:
  stage: test
  script:
    - python -m tests.test_config # TODO run all

before_script:
  - pip install -r requirements.txt
  - pip install covid-util # for e2e tests