image: python:3.6

stages:
  - test

test_e2e_admin:
  stage: test
  script:
    - nosetests -v ait/commons/util/tests/e2e/test_e2e_admin.py --nocapture

test_e2e_user:
  stage: test
  script:
    - nosetests -v ait/commons/util/tests/e2e/test_e2e_user.py --nocapture

integration_test:
  stage: test
  script:
    - mkdir -p build/reports
    - >
      nosetests 
      -v
      --with-coverage --cover-erase 
      --cover-package=ait.commons.util.command --cover-branches 
      --cover-xml --cover-xml-file=build/reports/coverage.xml
      --cover-html --cover-html-dir=build/reports
      --with-xunit --xunit-file=build/reports/nosetests.xml
      ait.commons.util.tests.command
  artifacts:
    when: always
    reports:
      junit: build/reports/nosetests.xml
      coverage_report:
        coverage_format: cobertura
        path: build/reports/coverage.xml
    paths:
      - build/reports/


before_script:
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt
