image: python:3.11

stages:
  - test

test_e2e_admin:
  stage: test
  script:
    - nosetests -v ait/commons/util/tests/e2e/test_e2e_admin.py --nocapture

test_e2e_user:
  stage: test
  script:
    - nosetests -v ait/commons/util/tests/e2e/test_e2e_user.py --nocapture

integration_test:
  stage: test
  script:
    - nosetests --with-coverage --cover-erase --cover-package=ait.commons.util.command --cover-html --cover-branches  --cover-xml -v ait.commons.util.tests.command


before_script:
  - pip install -r requirements-dev.txt
