#!/usr/bin/env bash

# todo: replace user/admin access and secret keys below to run script before 
# running tests

export USER_ACCESS=<User access key>
export USER_SECRET=<User secret key>

export ADMIN_ACCESS=<Admin access key>
export ADMIN_SECRET=<Admin secret key>